image: tmaier/docker-compose:latest
services:
  - docker:dind

stages:
  - test

test:
  stage: test
  script:
    - cd test
    - >
      docker-compose up
      --build
      --abort-on-container-exit
      --exit-code-from tap-test
      tap-test
    - >
      docker-compose up
      --build
      --abort-on-container-exit
      --exit-code-from mocha-test
      mocha-test
