image: tmaier/docker-compose:latest
services:
  - docker:dind

stages:
  - test
  - deploy

mocha-test:
  stage: test
  script:
    - cd test
    - mkdir fixtures/output
    - >
      docker-compose up
      --build
      --abort-on-container-exit
      --exit-code-from mocha-test
      mocha-test

tap-test:
  stage: test
  script:
    - cd test
    - mkdir fixtures/output
    - >
      docker-compose up
      --build
      --abort-on-container-exit
      --exit-code-from tap-test
      tap-test

deploy:
  stage: deploy
  script:
    - docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
    - docker-compose build beamish-runner
    - docker tag beamish/runner:${CI_COMMIT_TAG:-latest} beamish/runner:latest
    - docker-compose push beamish-runner
  only:
    - tags
