version: "3.2"
services:
  build-beamish:
    build:
      context: .
    image: beamish:latest

  build-beamish-FnHarness:
    build:
      context: .
      dockerfile: Dockerfile-FnHarness
    image: beamish-fnharness:latest

  build-beamish-grpc-harness-openfaas:
    build:
      context: .
      dockerfile: Dockerfile-harness-openfaas
    image: beamish-grpc-harness-openfaas:latest

  build-beamish-harness-openfaas:
    build:
      context: ./openfaas/harness
    image: beamish-harness-openfaas:latest

  build-beamish-toolbox:
    build:
      context: .
      dockerfile: Dockerfile-toolbox
    image: beamish-toolbox:latest
