version: "3.4"
services:
  build-beamish:
    image: node:10.9.0-alpine
    volumes:
      - .:/usr/src/app
      - beamish-direct-runner-node-modules:/usr/src/app/node_modules

  build-beamish-FnHarness:
    build:
      context: .
      dockerfile: Dockerfile-FnHarness
    image: beamish-fnharness:latest

  build-beamish-grpc-harness-openfaas:
    build:
      context: .
      dockerfile: Dockerfile-harness-openfaas
    image: beamish-grpc-harness-openfaas:latest

  build-beamish-harness-openfaas:
    build:
      context: ./openfaas/harness
    image: beamish-harness-openfaas:latest

  beamish-runner:
    build:
      context: .
      dockerfile: Dockerfile-runner
      target: base
    image: beamish/runner:${CI_COMMIT_TAG:-dev}

  build-beamish-toolbox:
    build:
      context: .
      dockerfile: Dockerfile-toolbox
    image: beamish-toolbox:latest

volumes:
  beamish-direct-runner-node-modules:
    name: beamish-direct-runner-node-modules
    driver: local
