FROM node:10.11.0-alpine

# Install app dependencies as global node modules:
#
ENV NODE_PATH /usr/local/lib/node_modules

# Create app directory and set as working directory:
#
WORKDIR /usr/src/app

# Install Git so that we can install from GitLab:
#
RUN apk add --no-cache \
  git

# We need '-unsafe-perm' for grpc as described here:
#
#  https://github.com/grpc/grpc/issues/6435
#
RUN npm install -g -unsafe-perm \
  gitlab:beamish/direct-runner#semver:^{CI_COMMIT_TAG}

# Tidy up:
#
RUN npm cache clean --force

# The Node image should really have set this:
#
ENTRYPOINT ["node"]
CMD ["pipeline.js"]
