version: "3.4"
services:
  # Data described here:
  #
  #  https://dev.mysql.com/doc/employee/en/sakila-structure.html
  #
  db:
    image: genschsa/mysql-employees:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'college'
  mockserver:
    image: jamesdbloom/mockserver
    ports:
      - "1080:1080"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
  mocha-test:
    build:
      context: .
      dockerfile: Dockerfile-runner
      target: mocha-test
    image: beamish/runner:mocha-test
    depends_on:
      - db
      - mockserver
    command: --exit /usr/src/app/test/mocha
    ports:
      - "50051:50051"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/usr/src/app
  tap-test:
    build:
      context: .
      dockerfile: Dockerfile-runner
      target: tap-test
    image: beamish/runner:tap-test
    depends_on:
      - db
      - elasticsearch
    command: --no-timeout /usr/src/app/test/tap
    environment:
      DEBUG: ${DEBUG}
    volumes:
      - .:/usr/src/app
  mocha-shell:
    build:
      context: .
      dockerfile: Dockerfile-runner
      target: mocha-test
    image: beamish/runner:mocha-test
    depends_on:
      - db
    entrypoint: ["/bin/sh"]
    ports:
      - "50051:50051"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/usr/src/app
  tap-shell:
    build:
      context: .
      dockerfile: Dockerfile-runner
      target: tap-test
    image: beamish/runner:tap-test
    depends_on:
      - db
      - elasticsearch
      - mockserver
    entrypoint: ["/bin/sh"]
    volumes:
      - .:/usr/src/app
